In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\Angelo Gaerlan\Desktop\Data Science\Data Sets\Chicago COPA\chicago COPA cases 2021\copa-cases-summary.csv")

In [3]:
df.head(100)

,LOG_NO,COMPLAINT_DATE,ASSIGNMENT,CASE_TYPE,CURRENT_STATUS,CURRENT_CATEGORY,FINDING_CODE,POLICE_SHOOTING,BEAT,RACE_OF_COMPLAINANTS,SEX_OF_COMPLAINANTS,AGE_OF_COMPLAINANTS,RACE_OF_INVOLVED_OFFICERS,SEX_OF_INVOLVED_OFFICERS,AGE_OF_INVOLVED_OFFICERS,YEARS_ON_FORCE_OF_INVOLVED_OFFICERS,COMPLAINT_HOUR,COMPLAINT_DAY,COMPLAINT_MONTH
0,1092329,2019-01-12T10:44:54.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,7,1
1,1092328,2019-01-12T10:24:30.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,7,1
2,1092327,2019-01-11T22:30:46.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,6,1
3,1092326,2019-01-11T15:29:31.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,6,1
4,1092325,2019-01-11T15:18:16.000,COPA,Complaint,Pending Investigation,Excessive Force,NaN,No,1132,African American / Black | African American / ...,Female | Male,40-49 | 20-29,NaN,NaN,NaN,NaN,15,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1092232,2019-01-05T23:59:27.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,7,1
96,1092231,2019-01-05T18:21:38.000,COPA,Complaint,Pending Investigation,Excessive Force,NaN,No,725,African American / Black,Female,0-19,Hispanic | White,Male | Male,20-29 | 50-59,0-4 | 15-19,18,7,1
97,1092230,2019-01-05T17:59:40.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,7,1
98,1092229,2019-01-05T12:11:52.000,COPA,Complaint,Pending Investigation,Excessive Force,NaN,No,933,Hispanic,Female,Unknown,White,Male,20-29,0-4,12,7,1
99,1092227,2019-01-04T21:18:53.000,BIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,6,1

In [4]:
#Check all datatypes for each columns
df.dtypes

LOG_NO                                  int64
COMPLAINT_DATE                         object
ASSIGNMENT                             object
CASE_TYPE                              object
CURRENT_STATUS                         object
CURRENT_CATEGORY                       object
FINDING_CODE                           object
POLICE_SHOOTING                        object
BEAT                                   object
RACE_OF_COMPLAINANTS                   object
SEX_OF_COMPLAINANTS                    object
AGE_OF_COMPLAINANTS                    object
RACE_OF_INVOLVED_OFFICERS              object
SEX_OF_INVOLVED_OFFICERS               object
AGE_OF_INVOLVED_OFFICERS               object
YEARS_ON_FORCE_OF_INVOLVED_OFFICERS    object
COMPLAINT_HOUR                          int64
COMPLAINT_DAY                           int64
COMPLAINT_MONTH                         int64
dtype: object

# CHECKING IF INTERESTING INFORMATION IN BIA COMPLAINTS HAVE BEEN REMOVED FROM THE DATASET

In [5]:
#query all complaints which from the BIA
bia_assignments = df[df.ASSIGNMENT=="BIA"]

In [6]:
'''
Given all the BIA assignments, calculate %missing for each column that contains relevant 
complaint data such as subject race and investigation status.
'''
(bia_assignments.drop(['COMPLAINT_HOUR','COMPLAINT_DAY','COMPLAINT_MONTH',"LOG_NO","COMPLAINT_DATE","ASSIGNMENT"], axis=1).isnull().sum())/len(bia_assignments)*100

CASE_TYPE                              100.0
CURRENT_STATUS                         100.0
CURRENT_CATEGORY                       100.0
FINDING_CODE                           100.0
POLICE_SHOOTING                        100.0
BEAT                                   100.0
RACE_OF_COMPLAINANTS                   100.0
SEX_OF_COMPLAINANTS                    100.0
AGE_OF_COMPLAINANTS                    100.0
RACE_OF_INVOLVED_OFFICERS              100.0
SEX_OF_INVOLVED_OFFICERS               100.0
AGE_OF_INVOLVED_OFFICERS               100.0
YEARS_ON_FORCE_OF_INVOLVED_OFFICERS    100.0
dtype: float64

<b> All BIA complaints have no information other than the date of the incident and log number. </b>

# FOR NON-BIA COMPLAINTS, CALCULATE THE % MISSING FOR EACH COLUMN

In [7]:
non_bia_complaints = df[df.ASSIGNMENT!="BIA"]

In [8]:
non_bia_complaints.isnull().sum()/len(non_bia_complaints)*100

LOG_NO                                  0.000000
COMPLAINT_DATE                          0.000000
ASSIGNMENT                              0.000000
CASE_TYPE                               0.000000
CURRENT_STATUS                          0.000000
CURRENT_CATEGORY                        0.305655
FINDING_CODE                            5.043301
POLICE_SHOOTING                         0.000000
BEAT                                    0.000000
RACE_OF_COMPLAINANTS                    6.469689
SEX_OF_COMPLAINANTS                     6.469689
AGE_OF_COMPLAINANTS                     6.469689
RACE_OF_INVOLVED_OFFICERS              25.938190
SEX_OF_INVOLVED_OFFICERS               25.938190
AGE_OF_INVOLVED_OFFICERS               25.938190
YEARS_ON_FORCE_OF_INVOLVED_OFFICERS    25.938190
COMPLAINT_HOUR                          0.000000
COMPLAINT_DAY                           0.000000
COMPLAINT_MONTH                         0.000000
dtype: float64

# OBTAIN THE UNIQUE VALUES FOR ORGANIZATIONS THAT ACCEPT COMPLAINTS

In [9]:
df.ASSIGNMENT.value_counts()

BIA     57935
IPRA    21953
COPA     1603
Name: ASSIGNMENT, dtype: int64

There are three organizations that accept complaints: BIA, IPRA, and COPA. The majority of complaints are from the BIA; however, interesting infomration such as races, sex, and age of officers involved have been ommited from the dataset.

# BASIC DATA CLEANING

In [10]:
'''
NOTE: More complicated data cleaning can be found in sections below.
'''

#convert COMPLAINT_DATE columns to datetime
df['COMPLAINT_DATE'] = pd.to_datetime(df['COMPLAINT_DATE'])

#extract year from timestamp
df['year'] = df['COMPLAINT_DATE'].apply(lambda x: x.year)

# ADD NO. OF POLICE OFFICERS AND POLICE OFFICER RACE COUNT COLUMNS

This section aims to add new columns that provide a count for each officer race. The problem is the columns containing information about officer races "RACE_OF_INVOLVED_OFFICERS" is the values are structured like this:

'Hispanic | Hispanic | White | African American / Black | African American / Black | African American / Black'
    
In this case, there are 6 officers involved in a complaint. The races of these 6 officers are: 2 Hispanic, 1 White, and 
3 African Americans/Blacks. 

In the current state of the officer races columns, the information is unusable and very dirty. To circumvent this problem, I will create 7 new columns containing the counts of each officer's race involved in a complaint. These are the following:
    
1. num_black_officers 
2. num_native_officers
3. num_asian_officers
4. num_hispanic_officers
5. num_unknown_officers
6. num_white_officers
7. num_police_officers - number of police officers involved in a complaint

In [11]:
'''
Confirm all possible races for RACE_OF_INVOLVED_OFFICERS.

All possible races for officers involved are:

1. African American / Black
2. American Indian or Alaskan Native
3. Asian or Pacific Islander
5. Hispanic
6. Unknown 
7. White
'''

s1 = set()
for race in df.RACE_OF_INVOLVED_OFFICERS:
    if str(race) != 'nan':
        s1.update(set(race.split("|")))

s1

{' African American / Black',
 ' African American / Black ',
 ' American Indian or Alaskan Native',
 ' American Indian or Alaskan Native ',
 ' Asian or Pacific Islander',
 ' Asian or Pacific Islander ',
 ' Hispanic',
 ' Hispanic ',
 ' Unknown',
 ' Unknown ',
 ' White',
 ' White ',
 'African American / Black',
 'African American / Black ',
 'American Indian or Alaskan Native',
 'American Indian or Alaskan Native ',
 'Asian or Pacific Islander',
 'Asian or Pacific Islander ',
 'Hispanic',
 'Hispanic ',
 'Unknown',
 'Unknown ',
 'White',
 'White '}

In [12]:
'''
This algorithm below adds the 6 columns:

1. num_black_officers 
2. num_native_officers
3. num_asian_officers
4. num_hispanic_officers
5. num_unknown_officers
6. num_white_officers


HOW IT WORKS:

1. Split the string delimited by '|'. NOTE: df.str.split('|') returns a list. 
2. Strip each element of the list to remove spaces in front and the back of the string. This is a crucial 
   cleaning step because this allows us to count the number of occurrences of each race.
3. Map the function list.count(officer_race) to count the occurances of each race. This step converts 
   the list to an integer.
'''


possible_officer_races = ['African American / Black',
                          'American Indian or Alaskan Native',
                          'Asian or Pacific Islander',
                          'Hispanic',
                          'Unknown', 
                          'White']


for officer_race in possible_officer_races:
    non_bia_complaints[officer_race] =  non_bia_complaints.RACE_OF_INVOLVED_OFFICERS.str.split("|") \
                                       .apply(lambda x:list(map(str.strip, x)) if str(x)!='nan' else None) \
                                       .apply(lambda x: x.count(officer_race) if x!=None else None)

C:\Users\ANGELO~1\AppData\Local\Temp/ipykernel_16300/1737654057.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_bia_complaints[officer_race] =  non_bia_complaints.RACE_OF_INVOLVED_OFFICERS.str.split("|") \

In [13]:
'''
The algorithm below adds the "num_police_officers" column.

HOW IT WORKS:

1. Split the string by "|". NOTE: df.str.split('|') returns a list. 
2. Apply the len() function to each list. This transforms the list into an integer that represents 
   the number of police officers involved in a case.
'''
    
non_bia_complaints["num_police_officers"] = non_bia_complaints.RACE_OF_INVOLVED_OFFICERS.str.split("|") \
                                            .apply(lambda x: len(x) if str(x)!="nan" else None)

C:\Users\ANGELO~1\AppData\Local\Temp/ipykernel_16300/2103671552.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_bia_complaints["num_police_officers"] = non_bia_complaints.RACE_OF_INVOLVED_OFFICERS.str.split("|") \

In [14]:
'''
Rename the 7 columns created 1 cell above to more meaningful names.
'''

non_bia_complaints.rename(columns={'African American / Black':'num_black_officers',
                           'American Indian or Alaskan Native':'num_native_officers',
                           'Asian or Pacific Islander':'num_asian_officers',
                           'Hispanic':'num_hispanic_officers',
                           'Unknown':'num_unknown_officers',
                           'White':'num_white_officers'},inplace=True)

C:\Users\Angelo Gaerlan\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [15]:
'''
This cell shows how the new officer columns look like.
'''

non_bia_complaints[['num_black_officers','num_native_officers','num_asian_officers','num_hispanic_officers','num_unknown_officers','num_white_officers','num_police_officers']]

,num_black_officers,num_native_officers,num_asian_officers,num_hispanic_officers,num_unknown_officers,num_white_officers,num_police_officers
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0.0,0.0,1.0,0.0,0.0,0.0,1.0
24,0.0,0.0,2.0,0.0,0.0,4.0,6.0
...,...,...,...,...,...,...,...
81476,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81479,0.0,0.0,0.0,0.0,0.0,1.0,1.0
81480,0.0,0.0,0.0,0.0,0.0,2.0,2.0
81488,0.0,0.0,0.0,0.0,0.0,1.0,1.0
81490,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# ADD NO. OF COMPLAINANTS AND NO OF COMPLAINANTS BY RACE COLUMNS

This section aims to add new columns that count each complainant's race. The problem is the columns containing information about complainant races "RACE_OF_COMPLAINANTS" is the values are structured like this:

'Hispanic | Hispanic | White | African American / Black | African American / Black | African American / Black'
    
In the case above, there are 6 complainants involved in a complaint. These 6 complainants are 2 Hispanic, 1 White, and 3 African Americans/Blacks. 

In the current state of the complainant races columns, the information is unusable and very dirty. To circumvent this problem, I will create 7 new columns containing the counts of each complainant's race involved in a single complaint. These are the following:

1. num_black_complainants
2. num_native_complainants
3. num_asian_complainants
4. num_hispanic_complainants
5. num_unknown_complainants
6. num_white_complainants
7. num_complainants - number of complainants involved in a case.

In [16]:
'''
Confirm all possible values for RACE_OF_COMPLAINANTS.

All possible races for complainants involved are:

1. African American / Black
2. American Indian or Alaskan Native
3. Asian or Pacific Islander
5. Hispanic
6. Unknown 
7. White
'''

s1 = set()
for race in df.RACE_OF_COMPLAINANTS:
    if str(race) != 'nan':
        s1.update(set(race.split("|")))

#set containing all unique races of complainants
complainants = set([x.strip() for x in list(s1)])

print(complainants)

{'American Indian or Alaskan Native', 'Hispanic', 'Asian or Pacific Islander', 'African American / Black', 'Unknown', 'White'}

In [17]:
'''
This algorithm below adds 6 columns:

1. num_black_complainants
2. num_native_complainants
3. num_asian_complainants
4. num_hispanic_complainants
5. num_unknown_complainants
6. num_white_complainants

HOW IT WORKS:

1. Split the string delimited by '|'. NOTE: df.str.split('|') returns a list. 
2. Strip each element of the list to remove spaces in front and the back of the string. This is a crucial 
   cleaning step because this allows us to count the number of occurrences of each race.
3. Map the function list.count(complainant_race) to count the occurrences of each race. This step converts 
   the list to an integer.
'''



#all unique races in the entire complianant race column
possible_complainant_races = ['African American / Black',
                              'American Indian or Alaskan Native',
                              'Asian or Pacific Islander',
                              'Hispanic',
                              'Unknown',
                              'White']

#add columns for the number of compainants of a specific race. This will create a race count for each of the races in the list above.
for complainant_race in possible_complainant_races:
    non_bia_complaints[complainant_race+"_complainant"] =  non_bia_complaints.RACE_OF_COMPLAINANTS.str.split("|") \
                                           .apply(lambda x:list(map(str.strip, x)) if str(x)!='nan' else None) \
                                           .apply(lambda x: x.count(complainant_race) if x!=None else None)

C:\Users\ANGELO~1\AppData\Local\Temp/ipykernel_16300/860120515.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_bia_complaints[complainant_race+"_complainant"] =  non_bia_complaints.RACE_OF_COMPLAINANTS.str.split("|") \

In [18]:
'''
The algorithm below adds the "num_complainants" column.

HOW IT WORKS:

1. Split the string by "|". NOTE: df.str.split('|') returns a list. 
2. Apply the len() function to each list. This transforms the list to an integer representing 
   the number of complainants involved in a case.
'''

non_bia_complaints["num_complainants"] = non_bia_complaints.RACE_OF_COMPLAINANTS.str.split("|") \
                                            .apply(lambda x: len(x) if str(x)!="nan" else None)

C:\Users\ANGELO~1\AppData\Local\Temp/ipykernel_16300/2952774921.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_bia_complaints["num_complainants"] = non_bia_complaints.RACE_OF_COMPLAINANTS.str.split("|") \

In [19]:
'''
Rename the 7 columns created above with more meaningful names.
'''

non_bia_complaints.rename(columns={'African American / Black_complainant':'num_black_complainants',
                           'American Indian or Alaskan Native_complainant':'num_native_complainants',
                           'Asian or Pacific Islander_complainant':'num_asian_complainants',
                           'Hispanic_complainant':'num_hispanic_complainants',
                           'Unknown_complainant':'num_unknown_complainants',
                           'White_complainant':'num_white_complainants'},inplace=True)

C:\Users\Angelo Gaerlan\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [20]:
'''
This cell shows how the new complianant columns looks like.
'''

non_bia_complaints[['num_black_complainants','num_native_complainants',
                   'num_asian_complainants','num_hispanic_complainants','num_unknown_complainants','num_white_complainants',
                   'num_complainants']]

,num_black_complainants,num_native_complainants,num_asian_complainants,num_hispanic_complainants,num_unknown_complainants,num_white_complainants,num_complainants
4,2.0,0.0,0.0,0.0,0.0,0.0,2.0
16,1.0,0.0,0.0,0.0,0.0,0.0,1.0
22,1.0,0.0,0.0,0.0,0.0,0.0,1.0
23,0.0,0.0,0.0,1.0,0.0,0.0,1.0
24,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...
81476,0.0,0.0,0.0,0.0,0.0,1.0,1.0
81479,1.0,0.0,0.0,0.0,0.0,0.0,1.0
81480,1.0,0.0,0.0,0.0,0.0,0.0,1.0
81488,2.0,0.0,0.0,0.0,0.0,0.0,2.0
81490,0.0,0.0,0.0,1.0,0.0,0.0,1.0

# CHECK IF ALL COMPLAINANT RACE COUNT COLUMNS ARE WHOLE NUMBERS. THIS IS TO CHECK DATA INTEGRITY

In [21]:
'''
Print the number of integers in the race count columns for each complainant. This is performed 
to ensure that the values inside the race count columns are whole integers.

For example, its impossible to have 2.34674 Whites and 1.224 Asians involved in a complaint.

CONCLUSION:

Because the number of integers in each race count column equals the number of 
non-null entries in the original dataset, there are no float values in the race count columns. 
Therefore, complainant columns pass the data integrity test.
'''

test = non_bia_complaints[['RACE_OF_COMPLAINANTS']+list(non_bia_complaints.columns[-7:])]

notempty = test[test.notnull().all(axis=1)]

possible_complainant_races = ['African American / Black',
                              'American Indian or Alaskan Native',
                              'Asian or Pacific Islander',
                              'Hispanic',
                              'Unknown',
                              'White']

dropped = notempty.drop('RACE_OF_COMPLAINANTS',axis=1)

for complainant_race in dropped.columns:
    s = dropped[complainant_race].apply(lambda x: x.is_integer()).sum()
    print("{} -> {}".format(complainant_race,s))

num_black_complainants -> 22032
num_native_complainants -> 22032
num_asian_complainants -> 22032
num_hispanic_complainants -> 22032
num_unknown_complainants -> 22032
num_white_complainants -> 22032
num_complainants -> 22032

# SAVE non_bia_complaints dataframe to CSV

In [22]:
non_bia_complaints.to_csv("no_bia_with_officer_information.csv")

# ARE LOG NUMBERS UNIQUE?

In [23]:
len(non_bia_complaints['LOG_NO'].unique()) == len(non_bia_complaints)

True

# ARE LOG NUMBER UNIQUE (INCLUDING BIA ASSIGNMENTS)?

In [24]:
len(df['LOG_NO'].unique()) == len(df)

True

# MISCELLANEOUS

In [25]:
test = non_bia_complaints[['RACE_OF_COMPLAINANTS']+list(non_bia_complaints.columns[-7:])]

In [26]:
notempty = test[test.notnull().all(axis=1)]

In [27]:
x = notempty[notempty.num_complainants>=3].sample(n=20)

In [28]:
x

,RACE_OF_COMPLAINANTS,num_black_complainants,num_native_complainants,num_asian_complainants,num_hispanic_complainants,num_unknown_complainants,num_white_complainants,num_complainants
66030,Hispanic | Unknown | Unknown | Hispanic | Unknown,0.0,0.0,0.0,2.0,3.0,0.0,5.0
72983,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
56017,Hispanic | Hispanic | Hispanic | Hispanic,0.0,0.0,0.0,4.0,0.0,0.0,4.0
77415,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
68676,Hispanic | Hispanic | Hispanic | Hispanic,0.0,0.0,0.0,4.0,0.0,0.0,4.0
62309,Hispanic | Hispanic | Hispanic | Hispanic,0.0,0.0,0.0,4.0,0.0,0.0,4.0
24650,African American / Black | African American / ...,8.0,0.0,0.0,0.0,0.0,0.0,8.0
73855,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
43048,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
68194,White | White | White,0.0,0.0,0.0,0.0,0.0,3.0,3.0
476,Unknown | Unknown | Unknown | Unknown,0.0,0.0,0.0,0.0,4.0,0.0,4.0
58331,African American / Black | African American / ...,4.0,0.0,0.0,0.0,0.0,0.0,4.0
69618,African American / Black | African American / ...,4.0,0.0,0.0,0.0,0.0,0.0,4.0
29205,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
68807,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
76439,African American / Black | African American / ...,5.0,0.0,0.0,0.0,0.0,0.0,5.0
35291,White | White | White,0.0,0.0,0.0,0.0,0.0,3.0,3.0
46098,African American / Black | Hispanic | African ...,2.0,0.0,0.0,1.0,0.0,0.0,3.0
42770,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0
37199,African American / Black | African American / ...,3.0,0.0,0.0,0.0,0.0,0.0,3.0

In [29]:
x.iloc[10]

RACE_OF_COMPLAINANTS         Unknown | Unknown | Unknown | Unknown
num_black_complainants                                         0.0
num_native_complainants                                        0.0
num_asian_complainants                                         0.0
num_hispanic_complainants                                      0.0
num_unknown_complainants                                       4.0
num_white_complainants                                         0.0
num_complainants                                               4.0
Name: 476, dtype: object

In [30]:
x.iloc[10]['RACE_OF_COMPLAINANTS'] #10

'Unknown | Unknown | Unknown | Unknown'